"""add phone column

Revision ID: 034f16ff5a62
Revises: 1a88a22a74a3
Create Date: 2026-08-06 11:31:34.793460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '034f16ff5a62'
down_revision: Union[str, Sequence[str], None] = '1a88a22a74a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'))
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='是否是超级用户'))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
