"""init user table

Revision ID: 7146ad33c8cf
Revises: 
Create Date: 2026-08-06 10:25:50.907139

"""
from typing import Sequence, Union  # noqa: UP035

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7146ad33c8cf'
down_revision: Union[str, Sequence[str], None] = None  # noqa: UP007
branch_labels: Union[str, Sequence[str], None] = None  # noqa: UP007
depends_on: Union[str, Sequence[str], None] = None  # noqa: UP007


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='用户id'),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=False, comment='用户名'),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False, comment='密码'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('is_delete', mysql.SMALLINT(), autoincrement=False, nullable=True, comment='是否删除'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###
